name: 'Review with AI'
on: 
  pull_request:

jobs:
  review:
    permissions:
      models: read
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Review
        id: inference
        uses: actions/ai-inference@v1.0.0
        with:
          system-prompt-file: ./system-prompt.txt
          prompt: |
            プルリクエストのタイトル: ${{ github.event.pull_request.title }}
            プルリクエストの本文: ${{ github.event.pull_request.body }}

      - name: Comment on PR
        env:
          RESPONSE: ${{ steps.inference.outputs.response }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "${RESPONSE}" > comment.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt 