name: 'Review with AI'
on: 
  pull_request:

jobs:
  review:
    permissions:
      models: read
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AI Review
        id: inference
        uses: actions/ai-inference@v1.0.0
        with:
          model: openai/gpt-4o
          system-prompt: |
            あなたはJavaコードレビュワーAIです。
            開発者が書いたJavaコードの「改善点」を端的に指摘し、それぞれに簡単な修正例もコードブロックで示してください。
            - コードの可読性
            - コーディング規約やベストプラクティス
            - バグや論理的な誤り
            - パフォーマンスやセキュリティ

            良い点は省略し、冗長な説明は避け、要点のみを箇条書きでまとめてください。
          prompt: |
            プルリクエストのタイトル: ${{ github.event.pull_request.title }}
            プルリクエストの本文: ${{ github.event.pull_request.body }}
          max-tokens: 1000 # レスポンスの最大トークン数

      - name: Comment on PR
        env:
          RESPONSE_FILE: ${{ steps.inference.outputs['response-file'] }}
          RESPONSE: ${{ steps.inference.outputs.response }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$RESPONSE_FILE" ] && [ -f "$RESPONSE_FILE" ]; then
            cat "$RESPONSE_FILE" > comment.txt
          else
            echo "$RESPONSE" > comment.txt
          fi
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt 