name: 'AI Review Demo'
on: pull_request

jobs:
  review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: AI Review
        id: inference
        uses: actions/ai-inference@v1.0.0
        with:
          system-prompt: |
            あなたはJavaコードレビュワーAIです。
            以下の観点でコードの修正点を1～2点、端的に指摘し、それぞれに簡単な修正例もコードブロックで示してください。
          prompt: |
            プルリクエストのタイトル: ${{ github.event.pull_request.title }}
            プルリクエストの本文: ${{ github.event.pull_request.body }}
          max-tokens: 1000

      - name: Comment on PR
        env:
          RESPONSE_FILE: ${{ steps.inference.outputs['response-file'] }}
          RESPONSE: ${{ steps.inference.outputs.response }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -n "$RESPONSE_FILE" ] && [ -f "$RESPONSE_FILE" ]; then
            cat "$RESPONSE_FILE" > comment.txt
          else
            echo "$RESPONSE" > comment.txt
          fi
          gh pr comment ${{ github.event.pull_request.number }} --body-file comment.txt 