name: 'AI inference'
on: workflow_dispatch

jobs:
  inference:
    permissions:
      contents: read
      models: read
    runs-on: ubuntu-latest
    steps:
      - name: AI Inference
        uses: actions/ai-inference@v1.0.0
        with:
          prompt: 'こんにちは！AI-inferenceアクションのテストです。'
          model: 'gpt-4o-mini'

      - name: Show AI Response
        run: echo "${{ steps.inference.outputs.response }}" 