name: Weekly Release Notes

on:
  schedule:
    - cron: '0 0 * * 1' # 毎週月曜日 0:00 UTC に実行
  workflow_dispatch:

jobs:
  summarize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      models: read
    steps:
      - uses: actions/checkout@v4

      - name: Fetch merged PRs in the past 7 days
        id: fetch_prs
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();
            const prs = await github.paginate(github.rest.pulls.list, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              per_page: 100
            });
            const merged = prs.filter(pr =>
              pr.merged_at &&
              pr.merged_at > since &&
              pr.base.ref === 'main'
            );

            let summary = '';
            for (const pr of merged) {
              const files = await github.paginate(github.rest.pulls.listFiles, {
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number
              });

              const fileList = files.map(f => `- ${f.filename} (${f.status})`).join('\n');
              summary += `### ${pr.title}\n${pr.body || 'No description.'}\n\n**Files changed:**\n${fileList}\n(PR #${pr.number})\n\n`;
            }

            fs.writeFileSync('merged_prs.md', summary);

      - name: Read prompt from file
        id: read_prompt
        run: |
          {
            echo "prompt<<EOF"
            cat merged_prs.md
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Summarize with AI
        id: ai
        uses: actions/ai-inference@v1.0.0
        with:
          model: openai/gpt-4o
          system-prompt: |
            あなたはちょっとユーモアのあるリリースノート職人です。
            以下は、先週mainにマージされたPRたちの情報です。
            どんな変化があったか、カテゴリごとにわかりやすく整理して、
            Markdownで読みやすく、ちょっと楽しくまとめてください。
          prompt: ${{ steps.read_prompt.outputs.prompt }}
          max-tokens: 1000

      - name: Save AI output to file
        env:
          RESPONSE: ${{ steps.ai.outputs.response }}
        run: |
          echo "${RESPONSE}" > weekly-release-notes.md

      - name: Notify to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          TITLE="Weekly Release Notes - $(date '+%Y-%m-%d')"
          BODY=$(cat weekly-release-notes.md)
          PAYLOAD=$(jq -n --arg title "$TITLE" --arg body "$BODY" '
            {
              blocks: [
                { "type": "header", "text": { "type": "plain_text", "text": $title } },
                { "type": "section", "text": { "type": "mrkdwn", "text": $body } }
              ]
            }
          ')
          curl -X POST -H 'Content-type: application/json' --data "$PAYLOAD" "$SLACK_WEBHOOK_URL"
